Add rule in Makefile to avoid pitfall of "make foo" instead of "make bin/foo"
Avoid this confusion:

scameron@wombat ~/github/space-nerds-in-space $ make snis_client
cc    -c -o snis_client.o snis_client.c
snis_client.c:30:21: fatal error: gtk/gtk.h: No such file or directory
compilation terminated.
<builtin>: recipe for target 'snis_client.o' failed
make: *** [snis_client.o] Error 1
scameron@wombat ~/github/space-nerds-in-space $ make snis_server
cc    -c -o snis_server.o snis_server.c
snis_server.c:47:17: fatal error: lua.h: No such file or directory
compilation terminated.
<builtin>: recipe for target 'snis_server.o' failed
make: *** [snis_server.o] Error 1
scameron@wombat ~/github/space-nerds-in-space $ make snis_limited_client
make: *** No rule to make target 'snis_limited_client'.  Stop.

Signed-off-by: Stephen M. Cameron <stephenmcameron@gmail.com>