Do not build mesh_viewer by default
Apparently, there's something screwed up about the SDL header
files (some mixing of SDL1 and SDL2 files included by mesh_viewer?
I don't know, but people complain:

  Not really a bug per-say as its a documentation issue.
  When compiling from instructions on the README.md file on a fresh install of
  Debian, a SDL dependency library is missing. Not sure if the .h file in
  mesh_viewer.c was missed with the conversion to SDL2 or if it still needs SDL1.

  mesh_viewer.c:5:21: fatal error: SDL/SDL.h: No such file or directory
   #include <SDL/SDL.h>
                     ^
  compilation terminated.
  Makefile:595: recipe for target 'mesh_viewer.o' failed

  To fix this issue run the following command from Debian/Ubuntu
  apt-get install libsdl-dev

And:

  It was missed. The code is making references to functions that are not in SDL2.

I'm not quite sure what "conversion to SDL2" is referring to (either I have
forgotten or there was no such thing)

In any case, to reduce the complaints, let's just not build mesh_viewer by default
since it isn't needed to run the game, and it's the only thing that uses SDL at all
at this time.

Signed-off-by: Stephen M. Cameron <stephenmcameron@gmail.com>